name: "deploy-frontend"
on:
  push:
    branches: ["main", "release", "develop"]
    paths:
      - ".github/workflows/deploy-frontend.yaml"
  workflow_run:
    workflows: ["test-frontend"]
    types:
      - completed
    branches: ["main", "release", "develop"]
  workflow_dispatch:
env:
  # General Env vars
  VITE_API_GATEWAY_URL: ${{ vars.VITE_API_GATEWAY_URL }}
  VITE_FILE_SERVICE_URL: ${{ vars.VITE_FILE_SERVICE_URL }}
  VITE_API_KEY: ${{ vars.VITE_API_KEY }}

  # DIDIT Specific Env vars
  VITE_DIDIT_API_KEY: ${{ vars.VITE_DIDIT_API_KEY }}
  VITE_DIDIT_WORKFLOW_ID: ${{ vars.VITE_DIDIT_WORKFLOW_ID }}
  VITE_DIDIT_CALLBACK_URL: ${{ vars.VITE_DIDIT_CALLBACK_URL }}

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: dawidd6/action-download-artifact@v3
        if: github.event_name == 'workflow_run'
        with:
          workflow: test-frontend.yaml
          name: frontend-build
          path: folder-contain-dist
          run_id: ${{ github.event.workflow_run.id }}

      - uses: actions/checkout@v4
        if: github.event_name == 'workflow_dispatch'

      - uses: actions/setup-node@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          node-version: 25

      - name: Build frontend
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd src/frontend
          npm install
          npm run build
          mkdir -p ../../folder-contain-dist
          cp -r dist ../../folder-contain-dist/

      - name: Copy folder dist to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "folder-contain-dist/dist"
          target: "/home/${{ secrets.VPS_USER }}/projects/frontend/"

      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/projects/frontend/
            sudo rm -rf /var/www/html/web-dev.lethanhcong.site/*
            sudo cp -r dist/* /var/www/html/web-dev.lethanhcong.site/
            sudo rm -rf dist
            sudo systemctl restart nginx
